### ISSUE TITLE
Archivist Off Switch

### ISSUE THREAD

**Issue by justinffortier** [XYOracleNetwork-v1/sdk-archivist-nodejs#54]
The Archivist should have a `yarn stop` command

**Comment by arietrouw** [comment]
This requires the full command line interaction system

**Comment by arietrouw** [comment]
Carter, does your app work add a start/stop system?

**Comment by carterharrison** [comment]
@justinffortier @arietrouw There is just a start and you can do ^C to stop. It is just a standard process, if you want it to run in a separate process you will need to use something like screen (like we do out our ec2s).
